### ISSUE TITLE
wma not working on 18.04 w/ "WORKSFORME" fix

### ISSUE THREAD

**Issue by qpl23** [FNA-XNA/FAudio#107]
Hi, Thanks a lot for your efforts!

Got here trying to make Skyrim Special Edition speak.. I'm on Proton 3.16 beta, built in the provided vagrant with the latest code from git, running under Neon User Edition (based on ubuntu 18.04)

So I encountered the "sound but no voices" issue in SSE (also, no music) and eventually wound up reading in this repo and compiling a replacement FAudio with ffmpeg support. After dropping my compiled .so in place,  NPCs were still silent. I installed SDL 2.09 manually from source, then recompiled FAudio, to make sure that wasn't a problem, but it made no difference.

I put in some debug printfs to see what was going on, and I found the avcodec_find_decoder() call around L85 in FAudio_ffmpeg.c was returning NULL.

I checked my libavcodec install and headers, and all that seemed to be in order. Googling, I found a SO question https://stackoverflow.com/questions/4091340/ffmpeg-compilation-problem-avcodec-find-decoder-always-returns-null with a similar problem.

Applying the solution found there, I was able to get music and voices working with the following diff against FAudio_ffmpeg.c:

```
diff --git a/src/FAudio_ffmpeg.c b/src/FAudio_ffmpeg.c
index f4b05b5..d86d811 100644
--- a/src/FAudio_ffmpeg.c
+++ b/src/FAudio_ffmpeg.c
@@ -68,6 +68,12 @@ uint32_t FAudio_FFMPEG_init(FAudioSourceVoice *pSourceVoice, uint32_t type)
        AVFrame *av_frame;
        AVCodec *codec = NULL;
        const char *typestring = "Unknown";
+       static int registered = 0;
+
+       if (!registered) {
+               avcodec_register_all();
+               registered = 1;
+       }
 
        LOG_FUNC_ENTER(pSourceVoice->audio)
        pSourceVoice->src.decode = FAudio_INTERNAL_DecodeFFMPEG;
```

After making this change NPC voices and music are both sounding good. I haven't tested beyond the start of the initial speech in the prisoners' wagon, so I can't vouch for anything beyond that point.

I'm not suggesting this is a good place to put this, since I don't really know how the code is layed out in FAudio. However it does seem for at least some current versions of libavcodec (specifically the one in ubuntu 18.04 repos) you really do need to call avcodec_register_all() to register the codecs you want to use. Hope it's of some use!

**Comment by qpl23** [comment]
> shotgun blast

LOL, you are correct! Though in times of maximal uncertainty, shotguns can be handy :)

What I don't get - and bear in mind I speak from a position of almost total ignorance - is how this is working for others, since the doc for the find_codec function stresses it will only find *registered* codecs, and no code in FAudio that I can see is registering anything.. 

Maybe this whole registering business is superseded in a more recent version of ffmpeg than my aging 18.04 distro grants me access to?

**Comment by flibitijibibo** [comment]
Yeah that surprised me too - but hey, no harm in having no-ops if it helps others, right?

But yeah, I wonder if this is why they removed the API - kind of a chicken and egg problem to register before you find, right?

**Comment by qpl23** [comment]
Well, the "shotgun" works for me.. I looked for examples of using the specific avcodec_register() function but couldn't get anything to work. Seems you would declare "extern AVCodec ff_wmav2_decoder" then call avcodec_register(&ff_wmav2_decoder), which compiled ok, but the steam-<id> log showed that ff_wmav2_decoder couldn't be resolved at runtime. 

I'll take another look tomorrow if I get time but given the deprecated status and the fact it only needs to run once I don't think register_all() is tragically burdensome, if using the specific registration call proves intractable.

**Comment by flibitijibibo** [comment]
The externs are probably samples where they expect you to have the AVCodec somehow... but if you can't find it with, er, find... I dunno. The problem with register_all is that most FFmpeg installations have something like 200 codecs, so loading them all at once is not great. (To get a sense of what I mean, load up your system's ffmpeg with `ffmpeg --version` and drink on every `--enable` you see)

**Comment by qpl23** [comment]
Well, the ff_(X)_foocoders are in allcodecs.c:  https://www.ffmpeg.org/doxygen/trunk/allcodecs_8c_source.html  ... but not too sure what to do to get it to link correctly.

I tried your drinking game, but after knocking back a short for every dll loaded by wine and skyrim, I was already too far gone to notice much of a hit :)

**Comment by flibitijibibo** [comment]
Closing due to old age... consider updating to FFmpeg 4 instead:

https://launchpad.net/~jonathonf/+archive/ubuntu/ffmpeg-4
