### ISSUE TITLE
Audio glitches with latest update

### ISSUE THREAD

**Issue by kakra** [FNA-XNA/FAudio#108]
Something broke between a756af43bd9729b164d9249aa9fa132a0237fe44 and 126cd0e5b5508c2f5317e81120fd517f3615174d.

I'm working on the https://github.com/kakra/wine-proton project, compiling `libFAudio` master as part of my proton branch.

With the current version of libFAudio I get crackling audio and several audio dropouts. It sounds like audio buffers play out of order or interleave with zero-filled buffers.

@flibitijibibo Do you need a recording sample? Should I try bisecting or do you suspect one commit which I could revert and try again?

**Comment by flibitijibibo** [comment]
Any chance that this can be distributed instead of Windows DLLs?

https://github.com/flibitijibibo/wine/pull/1

**Comment by kakra** [comment]
You mean like in "cherry picking the two top-most commits"? I think I have both of these in my branch (according to the commit title) but at an older version... I'll try. Thanks for pointing me at this.

**Comment by kakra** [comment]
Okay, I ran an interactive rebase of your branch against wine-4.0, copied the commit lines and injected those into my 4.1 proton branch. Seems to get rid of some commits from proton (conflicts resolved to empty commits). I'll test this. Thanks.

**Comment by kakra** [comment]
Looks (sounds) good so far... Let me test this for a while, my previous patches for replacing xaudio2 with FAudio in wine have been pretty old it seems. I'll close this if I can no longer reproduce it.

**Comment by flibitijibibo** [comment]
Closing since this appears to be solved... I couldn't find any reason for bugs to be introduced by this changeset anyhow:

https://github.com/FNA-XNA/FAudio/compare/a756af4...126cd0e

**Comment by kakra** [comment]
I can confirm... The problem didn't occur again.
