### ISSUE TITLE
[FAudio] Building on Ubuntu 16.04, can't find SDL2 libraries.

### ISSUE THREAD

**Issue by kaiwalyajoshi** [FNA-XNA/FAudio#109]
Hi @flibitijibibo, thanks for all the efforts on FAudio.

I've landed here as I'm trying to get [Wolfenstein: The New Order](https://github.com/ValveSoftware/Proton/issues/606) running with Proton and I'm encountering XAudio2 issues.

I've checked-out and attempted to build FAudio, I'm running into issues where `cmake` can't find the SDL2 libs. Could I get a slight helping hand in this aspect?

The SDL2 libs have been downloaded from APT:
`sudo apt install libsdl2-dev libsdl2-2.0-0`

The library and include files land here respectively:
- `/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so: symbolic link to libSDL2-2.0.so.0.4.0`
- `/usr/include/SDL2`

When building I get the following CMake errors:
```
-- no TARGET SDL2::SDL2, or SDL2, using variables
-- Configuring done
CMake Error at CMakeLists.txt:51 (add_library):
  Target "FAudio" links to item "-L/usr/lib/x86_64-linux-gnu -lSDL2 " which
  has leading or trailing whitespace.  This is now an error according to
  policy CMP0004.

CMake Error at CMakeLists.txt:51 (add_library):
  Target "FAudio" links to item "-L/usr/lib/x86_64-linux-gnu -lSDL2 " which
  has leading or trailing whitespace.  This is now an error according to
  policy CMP0004.

CMake Error at CMakeLists.txt:51 (add_library):
  Target "FAudio" links to item "-L/usr/lib/x86_64-linux-gnu -lSDL2 " which
  has leading or trailing whitespace.  This is now an error according to
  policy CMP0004.
```

Predictably `make` fails at the following line:
```
/home/kjoshi/temp/FAudio/src/FAudio_platform_sdl2.c:257:23: error: ‘SDL_AudioStream’ undeclared (first use in this function)
  SDL_FreeAudioStream((SDL_AudioStream*) resampler);
```

Looking at the [release notes for 19.02](https://github.com/FNA-XNA/FAudio/releases/tag/19.02), I see the following env-vars which I've tried to set:
```
export SDL2_INCLUDE_DIRS=/usr/include/SDL2
export SDL2_LIBRARIES=/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so
```

But I run into the same errors as above. I'm unfamiliar with `cmake` is there a way to get it to discover SDL2 in those installed locations?

Thanks again for your efforts.

**Comment by flibitijibibo** [comment]
Your SDL2 version is too old (~3 years too old) and you have a problem with at least one variable on your machine. As the error message states multiple times:

>Target "FAudio" links to item "-L/usr/lib/x86_64-linux-gnu -lSDL2 " **which has leading or trailing whitespace**.  This is now an error according to policy CMP0004.

Your distribution has a bug, please file this with them instead. In fact, this seems to have been a problem for almost a year, at least:

https://stackoverflow.com/questions/45730098/cmake-leading-or-trailing-whitespace-policy-cmp0004

**Comment by kaiwalyajoshi** [comment]
@flibitijibibo many thanks, I didn't know the Ubuntu bundled libSDL2 was too old.

[Wolfenstien: The New Order](https://github.com/ValveSoftware/Proton/issues/606) works now with the built libFAudio.so :tada: 

For anybody else that lands here, the following worked for me on Ubuntu 16.04
1. Get latest `cmake` Ubuntu 16.04 is capped at version `3.5` which is too old.
2. Install SDL from [source from here](https://wiki.libsdl.org/Installation)
3. Build FAudio here. (didn't encounter any errors or warnings, fix trailing whitespace issue with cmake from the link above if you hit that error)
4. Copy built `libFAudio.so` to Proton directories:
`cp libFAudio.so ~/.local/share/Steam/steamapps/common/Proton\ 3.16/dist/lib64`
5. Restart Steam.
6. Run Game.

:+1: thanks for this project and your help.
