### ISSUE TITLE
RFE: Set soname in library

### ISSUE THREAD

**Issue by mooninite** [FNA-XNA/FAudio#115]
Libraries typically have a soname version in the library and in their filename. FAudio does not have one.

Please set "libFAudio.so" to "libFAudio.so.0" or something similar.

**Comment by flibitijibibo** [comment]
Write it into the CMake file and it’s all yours.

**Comment by flibitijibibo** [comment]
Looked at SDL's versioning and threw this together, is this what you're looking for...?

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ba17d50..ed9d3bd 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -24,6 +24,12 @@ else()
        set(CMAKE_C_STANDARD 99)
 endif()
 
+# Version
+SET(LIB_MAJOR_VERSION "0")
+SET(LIB_MINOR_VERSION "19")
+SET(LIB_REVISION "02")
+SET(LIB_VERSION "${LIB_MAJOR_VERSION}.${LIB_MINOR_VERSION}.${LIB_REVISION}")
+
 # Build Type
 if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
        # By default, we use Release
@@ -113,6 +119,12 @@ if(MINGW)
        target_link_libraries(FAudio PRIVATE -static-libgcc)
 endif()
 
+# Soname
+set_target_properties(FAudio PROPERTIES OUTPUT_NAME "FAudio"
+       VERSION ${LIB_VERSION}
+       SOVERSION ${LIB_MAJOR_VERSION}
+)
+
 # XNA_Song Support
 if(NOT XNASONG)
        target_compile_definitions(FAudio PRIVATE DISABLE_XNASONG)
```

**Comment by mooninite** [comment]
Yes. I was fixing to send you a similar patch. Thanks!

**Comment by flibitijibibo** [comment]
Glad it was easier than I was expecting i to be, sorry for the trouble! (Never had to version anything before, crazy that I'm making Real People libraries now...)

https://github.com/FNA-XNA/FAudio/commit/bc6884e3b0d04b3c93d376e03289ce1cd09f354d
