### ISSUE TITLE
ARMv7 32bit NEON issue

### ISSUE THREAD

**Issue by albertodemichelis** [FNA-XNA/FAudio#117]
I'm building FAudio for android both 32 and 64 bits. The 32 bit version is failing because the neon implementation uses intrinsics that appear to be only present in ARM64 (eg. vuzp1q_f32).
As 32bit android is quite rare this days, I don't care much, but I just wanted to let you know.

**Comment by flibitijibibo** [comment]
Unless we can find an alternative to vuzp1q_f32 for 32-bit we'll probably have to disable the NEON stuff there. iOS is 64-bit only now, a Certain Other Mobile Platform supports 64-bit, and if Android 32-bit share is minimal then it looks like this won't affect much.

We need to add something before this line that checks for ARM32 and undefines `__ARM_NEON__` and sets `NEED_SCALAR_CONVERTER_FALLBACKS` to 1:

https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio_internal_simd.c#L57

**Comment by flibitijibibo** [comment]
NEON path is now ARM64-only:

https://github.com/FNA-XNA/FAudio/commit/2448eff4ee5d3024c63bf4620fa23abc7e2b55cf
