### ISSUE TITLE
Proton 4.2 changed the paths for libFAudio.so . Wiki might need an update for intructions.

### ISSUE THREAD

**Issue by igo95862** [FNA-XNA/FAudio#124]
I am particularly talking about this page: https://github.com/FNA-XNA/FAudio/wiki/FAudio-for-Proton

Running `tar --list --file proton_dist.tar.gz | grep libFAudio` on 4.2 gave me this list:
```
./lib/libFAudio.so
./lib/libFAudio.so.0
./lib/libFAudio.so.0.19.03
./lib64/libFAudio.so
./lib64/libFAudio.so.0
./lib64/libFAudio.so.0.19.03
```
Replacing just `./lib64/libFAudio.so` did not seem to make effect. I had to replace `libFAudio.so.0.19.03` and `libFAudio.so.0` on top of that for my FFmpeg libFAudio to work.

This could also be a bug on Valves end that might be fixed in the future.

**Comment by flibitijibibo** [comment]
Changed it to libFAudio.so.0
