### ISSUE TITLE
Dump raw SourceVoice buffers to files

### ISSUE THREAD

**Issue by NeroBurner** [FNA-XNA/FAudio#127]
I'd like to add a way to dump the raw buffers fed to a SourceVoice object to files to make it easier to work on files, which trigger assertions or cause other errors

I think it would be possible if we create a unique filename in [FAudio_CreateSourceVoice](https://github.com/FNA-XNA/FAudio/blob/8105923d29660364770bfa8812b2caf26abca907/src/FAudio.c#L228) and store it in [FAudioVoice](https://github.com/FNA-XNA/FAudio/blob/fe31f1b6b021f4896016dc2eacc85026005abdf9/src/FAudio_internal.h#L305). I think we can also write the header format for the wave-files in this step.

Then with each [FAudioSourceVoice_SubmitSourceBuffer](https://github.com/FNA-XNA/FAudio/blob/8105923d29660364770bfa8812b2caf26abca907/src/FAudio.c#L2004) we open the file with append and byte mode, append the buffers to the dump file and close the file again

- How could we create a unique name for each file?
- Which compile time options/environment variables should/could be used to change this behavior
- Have I forgotten something?

**Comment by flibitijibibo** [comment]
From yesterday's Discord logs...

>My advice is to to write a new file named after the source pointer, write a waveformatex to that file, then dump each SubmitSourceBuffer blob to the file and just keep appending forever
You’ll probably get some duds but not much you can do about it
Here’s some scrap i wrote for an undisclosed purpose https://gist.github.com/flibitijibibo/8d6d72cabd22444de957463428ac89f9

**Comment by NeroBurner** [comment]
Thanks a lot! I have no discord on my phone but wanted to get the idea out of my head. Sorry for the noise on the different channels

**Comment by NeroBurner** [comment]
for reference: fixed by: https://github.com/FNA-XNA/FAudio/pull/131
