### ISSUE TITLE
Load FFmpeg dynamically at runtime

### ISSUE THREAD

**Issue by TehFreek** [FNA-XNA/FAudio#128]
It is almost impossible to provide a compiled version of FAudio with FFmpeg support in Wine or Proton due to IP issues within FFmpeg. This is despite the fact that FFmpeg itself is easily available for almost every major Linux distro currently in use.

In the past software has (legitimately) gotten around this by runtime linking of the questionable software, e.g. using `dlopen(3)` et alia instead of passing the library name to the compiler. This is more work upfront for the developer since previous conditional compile statements now need to be replaced by checks for null or 0 results, but it saves hundreds to thousands of hours spent recompiling the software each time it is released.

**Comment by flibitijibibo** [comment]
If a real lawyer wants to chime in that’d be great, but considering we only use FFmpeg just for WMA I doubt that’ll fly.

**Comment by tuxayo** [comment]
Isn't WMA the biggest game compat blocker[1] after .net stuff ? (vague impression, might be inaccurate)

[1] excluding things out of Proton's control like anti cheats

**Comment by flibitijibibo** [comment]
>So that might be worth it.

That is entirely and completely the opposite of how liability is supposed to work:

https://en.wikipedia.org/wiki/Ford_Pinto#Cost-benefit_analysis,_the_Pinto_Memo

I'm not risking a lawsuit because people aren't willing to play something other than Skyrim/Fallout (which is like 99.9999999999% of WMA reports) until we find an appropriate license for WMA.

**Comment by tuxayo** [comment]
Sorry for the misunderstanding for loosing your time, I though that there were **also** technical/design reasons which the «I doubt that’ll fly.» would be about. That the necessary code changes weren't worth it for only supporting WMA.

I propose that I delete my comment and this one to remove the noise from this issue.

**Comment by NeroBurner** [comment]
Is the problem with the license of FFmpeg or with some patent/license of WMA?

**Comment by flibitijibibo** [comment]
Yes.

**Comment by flibitijibibo** [comment]
Closing due to old age - your time is better spent on researching the WMA format, both technological and legal. As of now this won’t actually help any of the situations in question.

**Comment by shmerl** [comment]
You don't risk anything by linking against ffmpeg, because you aren't implementing anything yourself. But if it's unclear, better ask legal council, for example from EFF or SFLC, they can help with that.

* https://www.softwarefreedom.org/about/contact/
* https://www.eff.org/pages/legal-assistance

**Comment by tuxayo** [comment]
@shmerl thanks for the pointers.

Something else to legally explore: which are countries are concerned by this? For example in Europe most US software patents wouldn't be valid: https://en.wikipedia.org/wiki/Software_patents_under_the_European_Patent_Convention

On the long run, we could have a version of Proton for countries were there is no WMA patent issue. And another version for other countries, like the USA. That way we would not be limited by the lowest common denominator. Like with graphic violence and nudity lead to various game versions depending on the country.

**Comment by tuxayo** [comment]
Or better, ask the user whether to enable depending on their laws, that leave the responsibility and legal research work to them.

That's what Ubuntu has been doing for years: having a checkbox in the installer about patent encumbered software like for MP3 support.
