### ISSUE TITLE
usage in Lutris

### ISSUE THREAD

**Issue by TRPB** [FNA-XNA/FAudio#136]
I've got it working perfectly in proton but thought I could do the same in lutris. I tried

```
cp ./libFAudio.so.0 /home/tom/.local/share/lutris/runners/wine/tkg-protonified-4.6-x86_64/lib64/
```

And set Skyrim SE to use `tkg-protonified-4.6`, but it hasn't loaded the new FAudio as I still get no voices. Is there an additional step required for lutris?

**Comment by flibitijibibo** [comment]
You’ll want to talk to the Lutris team about Lutris setup issues.

**Comment by flibitijibibo** [comment]
Closing due to old age but it sounds like this is a Lutris problem anyway.
