### ISSUE TITLE
The Child of Light: sound works only during cutscenes

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [FNA-XNA/FAudio#137]
The Child of Light has some issues with Faudio wine wrappers. I use Faudio 19.05, and the sound works only during cutscenes, but inside the game there is no sound in the menus or during gameplay.

**Comment by flibitijibibo** [comment]
Duplicate of https://github.com/ValveSoftware/Proton/issues/2463 (Even if this is vanilla Wine it's still the same issue)

**Comment by ahmed-elsayed2017** [comment]
No, the sound works without any problems with Wine-staging without Faudio wine wrappers.

**Comment by ahmed-elsayed2017** [comment]
A Story About My Uncle has the same issue. Both are 32bit, and DX9 games.
