### ISSUE TITLE
Fallout 4 - wav sounds above 16 bits cause freezes

### ISSUE THREAD

**Issue by OrdinaryMagician** [FNA-XNA/FAudio#141]
I noticed this happening with mods like [M2045 Magnum Revolver Rifle](https://www.nexusmods.com/fallout4/mods/17170). Some of the sounds are 24-bit or even 32-bit, which causes the game to freeze when firing the weapon. Converting them down to 16-bit stopped this from happening, at least.

**Comment by flibitijibibo** [comment]
24-bit should be supported, 32-bit integer not so much: https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio_internal.h#L679

Does it fix the issue if only 32-bit sounds are converted?

Another thing to look at is CreateSourceVoice, where we parse the WAVEFORMATEX structure: https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio.c#L243

**Comment by flibitijibibo** [comment]
Quick commit to dump PCM32 into the system: https://github.com/FNA-XNA/FAudio/commit/4e77b39782d0273615d6589fccda15cbb52edbf8

Assuming 24-bit already works, this may be all that's needed?

**Comment by OrdinaryMagician** [comment]
Looks like I can't build it, getting these linker errors:
```
/bin/ld: CMakeFiles/FAudio.dir/src/FAudio_internal.c.o: in function `FAudio_INTERNAL_DecodePCM32':
FAudio_internal.c:(.text+0x1d08): undefined reference to `FAudio_INTERNAL_Convert_S32_To_F32'
/bin/ld: CMakeFiles/FAudio.dir/src/FAudio_internal_simd.c.o: in function `FAudio_INTERNAL_InitSIMDFunctions':
FAudio_internal_simd.c:(.text+0x3c05): undefined reference to `FAudio_INTERNAL_Convert_S32_To_F32'
```

**Comment by flibitijibibo** [comment]
Beh, I hate that the linker doesn't do this by default. Fixed:

https://github.com/FNA-XNA/FAudio/commit/6ee986da49bd5adfd94ca40de465ac3b50a9f78e

**Comment by OrdinaryMagician** [comment]
Seems like it's still freezing, although it does get to play a split second of the sound.

**Comment by flibitijibibo** [comment]
This gets S32 wavs to play for me in our tests: https://github.com/FNA-XNA/FAudio/commit/335bb161bc98852f7cfa55ce22ebdd2cfdb85a0b

**Comment by OrdinaryMagician** [comment]
Can confirm over here. Thank you.

**Comment by jqadev** [comment]
@flibitijibibo @rbernon is there a chance that the sound issue described here
https://github.com/ValveSoftware/Proton/issues/308#issuecomment-962638138 can be solved soon?

**Comment by flibitijibibo** [comment]
Not without a patent license!
