### ISSUE TITLE
passing NULL to destination voice seems to be wrong behavior, according to the spec

### ISSUE THREAD

**Issue by TylerGlaiel** [FNA-XNA/FAudio#156]
https://github.com/FNA-XNA/FAudio/blob/3c8d281f5261ebcfcf594c31e60d57329603f9c5/src/FAudio.c#L1894-L1897

the spec states "Note  If the voice sends to a single target voice then specifying NULL will cause SetOutputMatrix to operate on that target voice."

this should be setting it to source->sends->pSends[0]->pOutputVoice, not voice->audio->master

unless the spec is wrong of course

**Comment by flibitijibibo** [comment]
Your version sounds more correct - will check this locally and commit today if nothing goes wrong.

**Comment by flibitijibibo** [comment]
Yup, that's a pretty blatant bug...

Pushed! https://github.com/FNA-XNA/FAudio/commit/4715d54a70ccefc42eb017e7a68b65941494f0e0
