### ISSUE TITLE
pkgconfig file has invalid prefix line

### ISSUE THREAD

**Issue by yokem55** [FNA-XNA/FAudio#159]
Compiling the current faudio from git using the gentoo live ebuild results in an invalid pkgconfig file:
```
[~]>cat /usr/lib64/pkgconfig/faudio.pc 
prefix=%PREFIX%
exec_prefix=${prefix}
libdir=${prefix}/lib64
includedir=${prefix}/include/FAudio

Name: faudio
Description: Accuracy-focused XAudio reimplementation for open platforms
Version:

Libs: -L${libdir} -lFAudio
Cflags: -I${includedir}
```
The prefix line `prefix=%PREFIX%` prevents the wine configure process from finding the the faudio libs. 

Interestingly, this bug is not present using the faudio-19.06 ebuild (which is pretty much identical to the live/git ebuild).

Here is the cmake command line gentoo uses when compiling faudio - 
```
cmake -C /var/tmp/portage/app-emulation/faudio-9999/work/faudio-9999-abi_x86_32.x86/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_BINDIR=bin -DCMAKE_INSTALL_INCLUDEDIR=include/FAudio -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DFORCE_ENABLE_DEBUGCONFIGURATION=OFF -DBUILD_TESTS=OFF -DBUILD_UTILS=OFF -DFFMPEG=ON -DXNASONG=OFF -DFFmpeg_LIBRARY_DIRS=/usr/lib -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/app-emulation/faudio-9999/work/faudio-9999-abi_x86_32.x86/gentoo_toolchain.cmake  /var/tmp/portage/app-emulation/faudio-9999/work/faudio-9999
```
Gentoo Bug report - https://bugs.gentoo.org/693404

**Comment by flibitijibibo** [comment]
The build system hasn't changed since 19.06 (other than MinGW stuff which shouldn't apply here). In fact, I didn't even know that file was generated...

Here's the install section of the CMake project: https://github.com/FNA-XNA/FAudio/blob/master/CMakeLists.txt#L411

**Comment by yokem55** [comment]
Okay, manually forced the the gentoo live/git ebuild to use the 19.06 commit/tag, and the bug reproduces there. I'll bark up the gentoo tree some more. Thanks!
