### ISSUE TITLE
 FACTCue_Destroy Confusion

### ISSUE THREAD

**Issue by alesliehughes** [FNA-XNA/FAudio#166]
In Function FACTCue_Destroy we start with this line

FAudio_PlatformLockMutex(pCue->parentBank->parentEngine->apiLock);

But then a few lines later we have 
if (pCue->parentBank != NULL)

If pCue->parentBank is NULL, then FAudio will have crashed in the first line.

So, How/When is the pCue->parentBank = NULL?

**Comment by flibitijibibo** [comment]
That was probably a throwaway line from before I started putting mutexes all over the place. For FNA games that was a pretty common occurrence since the GC made cleanup super inconistent, I don't know if that still happens nowadays.

**Comment by alesliehughes** [comment]
I'm currently looking at bug https://bugs.winehq.org/show_bug.cgi?id=41030  (Has a Demo).  And it's crashing after I apply all my patches from
https://github.com/alesliehughes/alesliehughes-wine-staging/tree/master/patches/xactengine-initial

Any chance you could have a look?

**Comment by flibitijibibo** [comment]
It'll probably be a couple months before I have the time, unfortunately.

**Comment by alesliehughes** [comment]
Let me know, if you do get a chance.  In the mean time, Ill continue to have a look at it.
