### ISSUE TITLE
Possible usage of null pointer

### ISSUE THREAD

**Issue by qarmin** [FNA-XNA/FAudio#186]
In line 1108 is used value of `ppCue`, but later in line 1121 is checked if isn't null, so there is possiblily to use invalid memory

https://github.com/FNA-XNA/FAudio/blob/df1349bd216a10191234c1c74315136be826c9a0/src/FACT.c#L1106-L1124

https://github.com/FNA-XNA/FAudio/blob/df1349bd216a10191234c1c74315136be826c9a0/src/FACT.c#L1067-L1085

**Comment by flibitijibibo** [comment]
If you want to write up the added `if` I can merge it whenever it's ready.

**Comment by flibitijibibo** [comment]
Wrote this in so we could have it for 20.05: https://github.com/FNA-XNA/FAudio/commit/4f99bb8ccd57f7dac465ab1fe4894a09a6ab5474
