### ISSUE TITLE
FAudioFXReverbParameters is missing SideDelay field.

### ISSUE THREAD

**Issue by rbernon** [FNA-XNA/FAudio#194]
According to https://naughter.wordpress.com/2015/05/24/changes-in-the-windows-10-sdk-compared-to-windows-8-1-part-two, this field has been added in XAudio 2.9 and it is missing from FAudioFXReverbParameters. 

I believe it is the root cause of Dragon Quest Builders 2 audio issues where the missing field makes the other parameters alias each other, and which ends up causing NaN values in the DspReverb code.

I'm not sure how this should be fixed, it will probably need some parameter conversion path depending on the client XAudio version, or depending on structure sizes if the former isn't possible.

**Comment by flibitijibibo** [comment]
It'd depend on how the reverb implementation changes, but at the API level it'd be adding FAudioFXReverbParameters9 and FAudioCreateReverb9, which would all end up using the same effect but the old version would wrap around the new version with SideDelay set to some default value. But a temporary fix to get the API scribbled in would be the opposite where it takes in the struct with SideDelay but discards the member in OnSetParameters (so we'll have to make that override function for real now).

**Comment by rbernon** [comment]
Alright, I had a quick look at OnSetParameters and I don't understand how it is supposed to work. It shouldn't modify the parameters as it's const void*, so the only thing it is supposed to do is to assert (as documented in https://docs.microsoft.com/fr-fr/windows/win32/api/xapobase/nf-xapobase-cxapoparametersbase-onsetparameters)?

**Comment by flibitijibibo** [comment]
Yeah, I think it would possibly involve overriding the memcpy portion as well, which is a bit sketchy... so I took a different approach while getting the busy work out of the way:

https://github.com/FNA-XNA/FAudio/commit/b83a87e9616d38866b038a3f26aa1a412c983d45

This _should_ work, but it does discard the new parameter, which will be a problem for 7.1 setups.

**Comment by rbernon** [comment]
Nice, thanks! I will try that.

**Comment by rbernon** [comment]
Yes that seems to be working nicely with the proper integration in Wine. Thanks again.
