### ISSUE TITLE
faudio_tests and utils segfault when alsa unavailable

### ISSUE THREAD

**Issue by h1z1** [FNA-XNA/FAudio#196]
Don't know enough about the code to know where to start.  Appears to fail when the device fails within ALSA.

```
$ ./faudio_tests 
ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
INFO: OpenAudioDevice failed: ALSA: Couldn't open audio device: Device or resource busy
test failed (/tmp/FAudio/tests/xaudio2.c:353): CreateMasteringVoice failed: 88960004
Segmentation fault (core dumped)
$
```

Expected result would be either an error with the device it's attempting to use or generic help?

**Comment by flibitijibibo** [comment]
This is expected behavior with ALSA as XAudio2 expects to be able to open a device more than once.

**Comment by h1z1** [comment]
A crash is expected?

**Comment by flibitijibibo** [comment]
Yes, it is expected. The expectation is that the OS failing to open a sound device is a fatal and unrecoverable error.

**Comment by h1z1** [comment]
It isn't fatal though.  The device is not available, that is a completely valid state.

**Comment by flibitijibibo** [comment]
You can fix the tests and utils individually if you want, but know that these are exclusively for developers and are not meant for general use - they're meant to diagnose very specific types of issues and nothing else. End users will not find any use for these programs, and developers will fix their OS should they not be suitable for active FAudio development.

**Comment by h1z1** [comment]
Not quite sure you're following.  From what I gathered the lack of error checking is from the library itself no?   testfilter for example does check for a return of 0 but it's bogus because other parts of the API force a return of 0 for some reason.   FAudioCreate for example

https://github.com/FNA-XNA/FAudio/blob/615530ee3ffbbd8825fc5666ecdcc5eb9651d99c/src/FAudio.c#L82-L83

**Comment by flibitijibibo** [comment]
That component isn't where the device is opened - you're going to be looking at FAudio_CreateMasteringVoice for error handling.

**Comment by h1z1** [comment]
Indeed, it was just an example.   FAudio_CreateMasteringVoice does the same thing though.

https://github.com/FNA-XNA/FAudio/blob/7f52bfb66b73cca2522537f45977886958a06324/src/FAudio.c#L732-L733

**Comment by flibitijibibo** [comment]
That's per the specification - those return codes are accurate. Your "bug" is not in FAudio, it's in the tests which expect CreateMasteringVoice to always return S_OK.

**Comment by h1z1** [comment]
As per [MS](https://docs.microsoft.com/en-us/windows/desktop/api/xaudio2/nn-xaudio2-ixaudio2masteringvoice):

Return value

   Returns S_OK if successful; otherwise, an error code. Returns
   ERROR_NOT_FOUND if no default audio device exists and NULL is passed
   in as the szDeviceId parameter.

**Comment by flibitijibibo** [comment]
The problem is that we do find a device, but it fails to open. If you can replicate a WASAPI shared device failing to open with the appropriate XAudio2 return code I can drop that into the line where opening fails, but as I've mentioned three other times, it's an application issue, not a library issue.

**Comment by h1z1** [comment]
We respectfully disagree but this is not the place for it.  I've forked the lib and modified it to catch this error and a few other conditions.  Thanks.
