### ISSUE TITLE
Fable III has no audio for dialog or the initial Microsoft logo

### ISSUE THREAD

**Issue by qsniyg** [FNA-XNA/FAudio#203]
Here's the log: https://drive.google.com/file/d/1DMF_cEmGXoKIKpSsgXmKdaitu7TuqIFE/view?usp=sharing

It will occasionally work for reasons I don't understand, but generally it will fail.

These lines appear to be of interest:

```
1438059.144:010c:trace:xaudio2:XA2SRC_SetOutputMatrix 0x2b84de8, (nil), 2, 8, 0x98b1e50, 0x0
INFO: 0x64e3b40 FAudioVoice_SetOutputMatrix 818ms API Enter: FAudioVoice_SetOutputMatrix
INFO: 0x64e3b40 FAudioVoice_SetOutputMatrix 818ms Mutex Lock: 0xc3f61d70
WARN: 

Assertion failure at FAudioVoice_SetOutputMatrix (./FAudio/src/FAudio.c:1928), triggered 1 time:
  'DestinationChannels == pDestinationVoice->master.inputChannels'

```

After commenting out the `FAudio_memcpy` call in `FAudioVoice_SetOutputMatrix` (as well as disabling the asserts, as it seems like the game does some weird things regarding audio while the alert dialog is launched, resulting in it occasionally working if closed during specific periods of time), it seems to "work" consistently.

The game runs fine with native xaudio2_6.dll (https://bugs.winehq.org/show_bug.cgi?id=49675)

My completely blind guess is that if DestinationChannels != DestinationVoice->channels, XAudio will selectively copy the channels instead of copying the buffer entirely. I'm guessing some tests might be needed to check which channels it copies (the first N channels?)

**Comment by flibitijibibo** [comment]
As far as I know this is a pretty blatant spec violation - it should probably return an error code like INVALID_CALL and not do anything.

**Comment by flibitijibibo** [comment]
Error checking added: https://github.com/FNA-XNA/FAudio/commit/ac512947b79c106beab0659fc02662c9ab6987a5

**Comment by qsniyg** [comment]
Can confirm the microsoft logo issue is fixed with that commit.

Dialog is still not fixed, but I see this from the log: `'0 && "xWMA is not supported!"'`, which indicates to me that this is due to missing 32-bit gstreamer libraries (arch linux doesn't provide them yet).

**Comment by flibitijibibo** [comment]
Sounds like this is fixed - if WMA sources emit similar assertion failures once Arch ships support, this can be reopened!

**Comment by qsniyg** [comment]
Will do, thanks for the quick fix! :)
