### ISSUE TITLE
FACTAudioEngine_PrepareStreamingWave to many parameters

### ISSUE THREAD

**Issue by alesliehughes** [FNA-XNA/FAudio#207]
This function doesn't match the XACT implementation, it has an extra parameter pbWaveData.

It's easy enough to work around when called.

Should we add a comment to state that this parameter shouldn't be/isn't used?

**Comment by flibitijibibo** [comment]
That or remove it since the symbol has no consumers yet, the check in Wine's configure.ac would need to be a bit more creative but this isn't quite like CommitChanges where existing code was using it.

**Comment by flibitijibibo** [comment]
On second thought, I can see Proton users trying to squish versions without doing a proper rebuild... sigh.

Marked as an ABI bug, let's hope a sufficiently-massive ABI break happens in XAudio 2.10 so I can finally fix some of these: https://github.com/FNA-XNA/FAudio/commit/ef5b62be6087f9ecb011d6a6b55d972d3c90ea8b
