### ISSUE TITLE
FACTAudioEngine_CreateStreamingWaveBank FACTStreamingParameters causes crash with IO on shutdown

### ISSUE THREAD

**Issue by alesliehughes** [FNA-XNA/FAudio#213]
IXACT3EngineImpl_CreateStreamingWaveBank which  though to call FACTAudioEngine_CreateStreamingWaveBank, which we create a FACTStreamingParameters and pass that through.

This maps "fakeParms.file" as a fake wrap_readfile_struct.
So at the start of FACT_INTERNAL_ParseWaveBank, the io parameter points to a wrap_readfile_struct from wine.  

Now when we shutdown FAudio, this WaveBank is destroyed, it assumes wavebank->io is a SDL_RWFromFile structure
thus calls FAudio_close. This assumption is causing a crash.

 How do you think we should fix this?

FYI: FACTAudioEngine_CreateInMemoryWaveBank does't have this issue, since it uses FAudio_memopen as the a parameter.

https://bugs.winehq.org/show_bug.cgi?id=49721

**Comment by flibitijibibo** [comment]
What is the line that fails?

**Comment by alesliehughes** [comment]
uint32_t FACTWaveBank_Destroy(FACTWaveBank *pWaveBank)
...
FAudio_close(pWaveBank->io);
