### ISSUE TITLE
Crash in Call of Duty: World at War

### ISSUE THREAD

**Issue by grapeharvest** [FNA-XNA/FAudio#220]
After starting a new game crashes randomly with

`err:seh:NtRaiseException Unhandled exception code c0000005 flags 0 addr 0x59adb3`

so most likely it's something like [this](https://bugs.winehq.org/show_bug.cgi?id=46918).

**Comment by flibitijibibo** [comment]
That doesn't say where the crash occurred - I don't see anything in that line suggesting it's us at all.
