### ISSUE TITLE
FAudio doesn’t generate a pkg-config file

### ISSUE THREAD

**Issue by Gcenx** [FNA-XNA/FAudio#224]
Compiling from source produces the library along with the needed headers but a pkg-config .pc file is not generated and I don’t see a template within the project.

Is this something you’d be willing to implement?, or is this something you’d rather leave up-to package maintainers.

The only project I’m aware of that checks pkg-config for FAudio currently is wine.

**Comment by flibitijibibo** [comment]
If someone wants to add it to CMakeLists.txt, sure. Nobody's said anything about until now. I strongly suggest looking at everybody's packages and looking for any patches related to this.

**Comment by ryandesign** [comment]
> Nobody's said anything about until now.

Not exactly true. The notion of an FAudio pkg-config file has previously come up in #159.

**Comment by flibitijibibo** [comment]
Looks like their preference was a manual file as well. I noticed that neither Fedora nor Debian has this file, and Arch also has a manual file that looks nothing like Gentoo's. Is this something we _should_ have in upstream? If it's not something that CMake can generate trivially I'm not sure it'd be a good idea.

**Comment by flibitijibibo** [comment]
It looks like we can do an FAudio.pc.in and use configure_file:

https://cmake.org/cmake/help/v3.18/command/configure_file.html

We can can copy SDL2 here that'd be my preference:

https://hg.libsdl.org/SDL/file/1b1fae168557/sdl2.pc.in
https://hg.libsdl.org/SDL/file/1b1fae168557/CMakeLists.txt

Won't make the same thing that others have made, but it'll have to do.

**Comment by Gcenx** [comment]
Arch is Arch, I'd checked the AUR package but not the standard version. The Gentoo package seem to be maintained by a wine contributor so I'd opted to copy what they'd done.

(you beat me to the SDL2 reference)

Having this within upstream is preferable so it can be taken advantage of, as not everyone/system will have headers/libraries within "standard" locations

Also if this does get added and documented, having the headers within /FAudio sub-directory would be ideal.

**Comment by flibitijibibo** [comment]
Just checking on this - I won't be able to write this up for quite a while, but if a packager wants to scribble this up I can review and merge it and CC other maintainers as needed.

**Comment by flibitijibibo** [comment]
Definite 100% ultimate last call for this - FAudio got no commits this month so this would pretty much be the only change we would push, making it a very very safe release to include this in.
