### ISSUE TITLE
cmake 3.5.2 build issue

### ISSUE THREAD

**Issue by orbea** [FNA-XNA/FAudio#226]
OS: `Slackware-14.2`
FAudio: `20.11`
cmake: `3.5.2`
gstreamer: `1.6.4`
gst-plugins-base: `1.6.4`

When building FAudio with an older cmake version and `-DGSTREAMER=ON` it will fail because `IMPORTED_TARGET` is not yet supported for the `pkg_check_modules` command.

Here we see that FAudio requires cmake `2.8.12` or newer.

https://github.com/FNA-XNA/FAudio/blob/585cc0f406c75d85f7052b380909b05556034869/CMakeLists.txt#L3

And `IMPORTED_TARGET` is only used for detecting the gstreamer dependency.

https://github.com/FNA-XNA/FAudio/blob/585cc0f406c75d85f7052b380909b05556034869/CMakeLists.txt#L145

Looking at the cmake docs the first version that documents `IMPORTED_TARGET` is `3.6`.

https://cmake.org/cmake/help/v3.6/module/FindPkgConfig.html

The documents for `2.8` don't even seem to be present.

I suggest to these possible steps can be done to resolve this.

* Raise the minimum cmake version requirement to something newer.
* And/or don't use `IMPORTED_TARGET`.

The build will succeed if `-DGSTREAMER=ON` is not set.

Error:
```
-- The C compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for modules 'IMPORTED_TARGET;gstreamer-1.0'
--   No package 'IMPORTED_TARGET' found
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:363 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
  CMakeLists.txt:145 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

**Comment by flibitijibibo** [comment]
If we can get away with replacing it, great, otherwise if we have no other choice we can bump to 3.6 as CentOS provides a new enough `cmake3` package for this to be okay.

**Comment by orbea** [comment]
This seems to at least build on Slackware current, but it fails on the older Slackware 14.2 with gstreamer build issues. I presume a minimal gstreamer version needs to be specified too. It may not be worth building with gstreamer support on Slackware 14.2...
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index bb57a67..28a19d5 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -142,9 +142,9 @@ if(GSTREAMER)
 
 	# Find GStreamer
 	find_package(PkgConfig)
-	pkg_check_modules(GST REQUIRED IMPORTED_TARGET gstreamer-1.0)
-	pkg_check_modules(GSTAUDIO REQUIRED IMPORTED_TARGET gstreamer-audio-1.0)
-	pkg_check_modules(GSTAPP REQUIRED IMPORTED_TARGET gstreamer-app-1.0)
+	pkg_check_modules(GST REQUIRED gstreamer-1.0)
+	pkg_check_modules(GSTAUDIO REQUIRED gstreamer-audio-1.0)
+	pkg_check_modules(GSTAPP REQUIRED gstreamer-app-1.0)
 
 	# Include/Link GStreamer...
 	target_include_directories(FAudio PRIVATE
@@ -153,9 +153,9 @@ if(GSTREAMER)
 		${GSTAPP_INCLUDE_DIRS}
 	)
 	target_link_libraries(FAudio PRIVATE
-            PkgConfig::GST
-            PkgConfig::GSTAUDIO
-            PkgConfig::GSTAPP
+            ${GST_LIBRARIES}
+            ${GSTAUDIO_LIBRARIES}
+            ${GSTAPP_LIBRARIES}
         )
 endif(GSTREAMER)
 
```

**Comment by flibitijibibo** [comment]
The CMake change makes sense to me - I believe we require GStreamer 1.10 or newer for that backend to work, if we can detect that as well it may solve both problems safely.

**Comment by orbea** [comment]
From my testing the earliest I can build FAudio is with gstrearmer `1,9.2` where `1.9.1` just lacks `gst_app_sink_try_pull_sample`.

I'll make a PR with this in a little bit.

**Comment by orbea** [comment]
For future reference this is the build error with gstreamer 1.9.1.
```
/tmp/SBo/FAudio-20.11/src/FAudio_gstreamer.c: In function 'FAudio_GSTREAMER_FillConvertCache':
/tmp/SBo/FAudio-20.11/src/FAudio_gstreamer.c:184:12: warning: implicit declaration of function 'gst_app_sink_try_pull_sample' [-Wimplicit-function-declaration]
   sample = gst_app_sink_try_pull_sample(
            ^
/tmp/SBo/FAudio-20.11/src/FAudio_gstreamer.c:184:10: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   sample = gst_app_sink_try_pull_sample(
          ^
[100%] Linking C shared library libFAudio.so
CMakeFiles/FAudio.dir/src/FAudio_gstreamer.c.o: In function `FAudio_GSTREAMER_DecodeBlock':
FAudio_gstreamer.c:(.text+0x265): undefined reference to `gst_app_sink_try_pull_sample'
collect2: error: ld returned 1 exit status
CMakeFiles/FAudio.dir/build.make:563: recipe for target 'libFAudio.so.0.20.11' failed
make[2]: *** [libFAudio.so.0.20.11] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/FAudio.dir/all' failed
make[1]: *** [CMakeFiles/FAudio.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
