### ISSUE TITLE
Severe sound lag in wine

### ISSUE THREAD

**Issue by 65a** [FNA-XNA/FAudio#233]
I'm using the latest wine from git.
I'm using the latest faudio from git locally, with gstreamer/libav support enabled.

Running skyrim with xaudio2_6 and xaudio2_7, the game runs as expected
Running skyrim with faudio (built-in), audio effects are delayed by 1-5 seconds

In both cases, audio quality is exceptional. The only problem I am seeing is an exceptional audio delay.

I can capture WINEDEBUG logs for this, but they are quite noisy. They do look substantially different between the versions.

**Comment by flibitijibibo** [comment]
You're most likely looking at something involving PULSE_LATENCY_MSEC and SDL, not FAudio itself - we just write to the OS output buffer that SDL gives us, we don't dig any deeper than that.

**Comment by 65a** [comment]
I tested with alsa and pulse backends, with and without pipewire. The problem follows only faudio/xaudio, not backend changes.

**Comment by 65a** [comment]
My first thought was that this was buffer bloat in the audio framework, hence testing with multiple different ones.

I'll capture WINEDEBUG, the output is quite different between them. The audio quality is perfect, just delayed with faudio. I'd prefer to use faudio for several reasons.

**Comment by flibitijibibo** [comment]
You will want to check with SDL separately then - we're nothing more than a sample mixer, so any delay of any kind is _always, at minimum_, one level below us.

**Comment by 65a** [comment]
Glad to dig more. I'm not sure if sound is actually globally delayed, which is complicated by that particular game using multiple audio systems. Some audio effects require libav decoding, not sure if the delayed ones are going in that path, which is probably another opportunity for shenanigans. Interestingly there is no delay in effects until actually playing the game using FAudio, which also makes me suspicious of multiple sound sources interacting poorly somewhere.

**Comment by flibitijibibo** [comment]
Doing a bit of spring cleaning...

This should be filed as an SDL bug if it's still an issue, but I would strongly recommend looking at Pipewire - even for working setups I noticed reduced latency just from using Pipewire's Pulse layer, I imagine the direct Pipewire driver in SDL 2.0.16 will be really good too. Either way, closing as NOTOURBUG.
