### ISSUE TITLE
FAudio.pc not good enough for gstreamer enabled build

### ISSUE THREAD

**Issue by j-r** [FNA-XNA/FAudio#235]
In a gstreamer enabled build the resulting libFAudio.so depends on several gstreamer symbols. Therefore linking using only the information from pgk-config --libs FAudio fails with missing symbols. An easy solution is to add

Requires: gstreamer-app-1.0 gstreamer-audio-1.0

to FAudio.pc for gstreamer enabled builds, but I'm not sure whether this is the best way. Perhaps it would be better for FAudio to dlopen the backend instead of exposing this (pretty large) dependency to its clients.

**Comment by flibitijibibo** [comment]
Sadly GStreamer is really weird about init/close, so dlopen may not be entirely possible to do safely (ignoring that we have to link to like 3-4 libraries on top of that):

https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio_gstreamer.c#L467-L474

As far as I know the current system works for distributions as well as Proton, but I'll CC the original authors of the .pc just in case (FNA doesn't care about this file): @orbea @Gcenx

**Comment by orbea** [comment]
@j-r Do you have a test case?

**Comment by Gcenx** [comment]
This may be correct and wouldn’t affect wine that would be pulling in gstreamer anyway.

**Comment by orbea** [comment]
I made a PR with the suggestion in the op, I don't see why not?

**Comment by j-r** [comment]
> @j-r Do you have a test case?

My test case was wine (after patching it to actually look for the right pkg-config file; s. [https://bugs.winehq.org/show_bug.cgi?id=50436](https://bugs.winehq.org/show_bug.cgi?id=50436)). The link test in wine configure fails with a gstreamer enabled FAudio build.

**Comment by orbea** [comment]
@j-r Would you mind testing the PR? Otherwise I can try later.

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FAudio/commit/d7c84f04b4a383aaa5c41101f62cb569e195f1ca
