### ISSUE TITLE
Unhandled exception if a global settings file is not loaded on initialization and a sound has a category

### ISSUE THREAD

**Issue by apartfromtime** [FNA-XNA/FAudio#258]
XACT3 by default allows sounds with categories set to be played regardless whether the global settings file (.xgs) has been loaded and passed to the parameters or left empty on initialization. 

When a sound with a category is played an exception is thrown here
https://github.com/FNA-XNA/FAudio/blob/0e91073e654128a5379160e8ebad381b44f6edc1/src/FACT_internal.c#L627

The engine succeeds in getting a category index from the base sound, but no categories have been loaded. I found this porting some code to FAudio.

**Comment by flibitijibibo** [comment]
Is this really the only thing that breaks? I would expect the entire codebase to fall apart, I have never seen that behavior attempted before. Does the offline documentation say this is possible and what the result is somewhere?

**Comment by apartfromtime** [comment]
> Is this really the only thing that breaks? I would expect the entire codebase to fall apart, I have never seen that behavior attempted before. Does the offline documentation say this is possible and what the result is somewhere?

Well that's the first thing that breaks. The documentation implies that the settings file is optional, the documentation also states all sounds belong to a root category called "Global", and the api basic steps omits any mention of a settings file, but there is a tutorial outlining categories and a game sample which makes use of categories from a setting file. The authoring tool by default generates three basic categories "Global", "Default" and "Music" for new projects and new sounds in a soundbank default to "Default", all three categories cannot be renamed or deleted only have their setting modified. From the documentation and the authoring tool, I'd suggest at the very least the "Global" sound category should be created and the "Default" and "Music" if a settings file isn't passed via parameters. But that's your call. Excellent project by the way, really appreciated. I'd have a go at implementing it myself, if you are too busy, but I don't know the project all that well.

**Comment by flibitijibibo** [comment]
If the source is available somewhere I'd love to see it - this is the first out of nearly 100 titles I've examined to attempt something like this. Otherwise you may be the only person that'll be able to verify the intended vs actual behavior. Fixing each crash one-by-one is probably not a bad way to go about it, the XACT implementation is wordy but almost 100% of the time the blunt, obnoxious patch is the correct answer. (Of course, I can also review changes as they happen!)

**Comment by apartfromtime** [comment]
The source example isn't from any shipped title, the source accompanied a book on games programming, the books first publication dates back almost a decade now, and amounts to a bare minimum example (similar to those found in the documentation). But the book was published, so I guess that counts as shipped code. The code is open source and can found here: http://www.programming2dgames.com/ and is covered by the CC3.0 Licence.

**Comment by flibitijibibo** [comment]
Took a look and I'm honestly surprised they didn't think to include the buffer in the example... but, this doesn't seem like a crazy thing to implement, so I took a wild guess:

https://github.com/FNA-XNA/FAudio/commit/8af74184e76247e2c44a4f8b3747c2c942e1251e

This _should_ be enough, but if not you're looking at that new block I wrote in there. Once that block is accurate this issue should be resolved.

**Comment by apartfromtime** [comment]
There is also a "Music" default, but yes this solves the issue.

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FAudio/commit/cb489e5059aecf679137b4812080714334dbc638
