### ISSUE TITLE
CMake FAudio config files do not respect cmake syntax

### ISSUE THREAD

**Issue by p01arst0rm** [FNA-XNA/FAudio#259]
Recently discovered this issue looking into problems with
users trying to compile with FAudio on the rpcs3 project.

this issue relates to the cmake config files. for example, the config
file is named `FAudio-config.cmake`. this is incorrect formatting for cmake,
as it is expecting a file in the format of `NameOfLibrary.cmake` or
`librarynamenocaps-config.cmake`. the upstream needs to make their
build export the file(s) either as FAudio.cmake or faudio-config.cmake

see also: https://github.com/RPCS3/rpcs3/pull/10536#pullrequestreview-704492917

**Comment by flibitijibibo** [comment]
Will let you handle this since you have a test case - once you have a fix it'll go in after a quick sanity check.

**Comment by p01arst0rm** [comment]
> Will let you handle this since you have a test case - once you have a fix it'll go in after a quick sanity check.

theres a couple of ways this can be fixed though. the easiest would just be changing the `project(FAudio C)` tag to `project(faudio C)`, or i could edit the config file definitions to stop using the project name to control the file name.

**Comment by flibitijibibo** [comment]
Changing the project name might cause some breakages, between those two the latter sounds safer.

**Comment by p01arst0rm** [comment]
alright, ill knock up a PR :)
