### ISSUE TITLE
Error compiling 21.11, SDL_assert undeclared

### ISSUE THREAD

**Issue by mooninite** [FNA-XNA/FAudio#275]
I am attempting to compile FAudio 21.11 for Fedora. Is this a known issue?

SDL2-devel-2.0.16-4.fc36

During compilation:

<pre>
/builddir/build/BUILD/FAudio-21.11/src/FAudio.c: In function 'FAudioSourceVoice_SubmitSourceBuffer':
/builddir/build/BUILD/FAudio-21.11/src/FAudio.c:3203:51: error: unterminated argument list invoking macro "SDL_assert"
 3203 | /* vim: set noexpandtab shiftwidth=8 tabstop=8: */
      |                                                   ^
In file included from /builddir/build/BUILD/FAudio-21.11/src/FAudio.c:27:
/builddir/build/BUILD/FAudio-21.11/src/FAudio_internal.h:166:23: error: 'SDL_assert' undeclared (first use in this function); did you mean 'SDL_sqrt'?
  166 | #define FAudio_assert SDL_assert
      |                       ^~~~~~~~~~
</pre>

**Comment by flibitijibibo** [comment]
This sounds like an issue with the build system - SDL_assert has been a part of SDL since 2.0, released 8 years ago, and has been a part of FAudio since the Git history began.

**Comment by mooninite** [comment]
21.09 and 21.10 compile successfully in the same build environment. :(

I'll keep looking.

**Comment by flibitijibibo** [comment]
If GStreamer is enabled (no longer required as of Wine 6.20), be sure to take in the latest tip - it's the same as 21.11 but with an added ) on a line.

**Comment by mooninite** [comment]
I'm building with GStreamer enabled. Fedora is on 6.18, but will soon be upgraded.

The issue is commit b591694. You're missing a ) in the change. I'll submit a PR.

**Comment by mooninite** [comment]
Ah, it's already fixed on master. Thanks!

See: de0c1f833c12a992af5c7daebe1705cd2c72f743
