### ISSUE TITLE
Saints Row 2 No Music

### ISSUE THREAD

**Issue by ukbeast** [FNA-XNA/FAudio#277]
Using wine wine-staging 7.0-rc1 on OpenSUSE and FAidio 21.11.

0108:fixme:xact3:IXACT3EngineImpl_Initialize pXAudio2 parameter not supported!
0108:fixme:xact3:IXACT3EngineImpl_Initialize pMasteringVoice parameter not supported!

**Comment by flibitijibibo** [comment]
Those FIXMEs are Wine messages - additionally that game is known to use WMA which means the issue lies in their MediaFoundation implementation.
