### ISSUE TITLE
Can't CMAKE Kubuntu 22.04

### ISSUE THREAD

**Issue by mpaccione** [FNA-XNA/FAudio#283]
Hi here is the error per following the README
```
mpaccione@mpaccione:~/FNA/build$ cmake ../
CMake Error: The source directory "/home/mpaccione/FNA" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

I got here because I was looking to build FAudio. I couldn't with winetricks because it wants wine32 and I figure im running things that are too new. This was to fix missing vocals in Skyrim at least that was the idea,

**Comment by flibitijibibo** [comment]
The CMake file is in the root of FAudio, not FNA.

In any case, FAudio won't be any help here - the stock configuration does not support WMA and the configuration that does is already included statically in upstream Wine. If you're on 7.0 or newer it's down to codec issues, which is separate from us.
