### ISSUE TITLE
tModLoader; Issues with FAudio/FNA

### ISSUE THREAD

**Issue by RealZyther** [FNA-XNA/FAudio#287]
Hi there! I and many others are encountering an FNA/FAudio sound issue within tModLoader 1.4.
A fellow encountering the same issue uploaded a video on youtube; https://youtu.be/khF6Z5Q57R0
(https://github.com/tModLoader/tModLoader/issues/2466) (https://github.com/tModLoader/tModLoader/issues/2323) 
I've also made GitHub tickets on tModLoader, but I've decided to make one here too since the issue is directly linked to FNA
---------------------------------------------------------------------------------------------------------------------------------------------------
My Hardware: **AMD RX** 580 | **AMD Ryzen** 7 (3700x) | 32GB Memory (2x16GB) | **B450 Motherboard**
DeCactuse Hardware: **AMD RX** 5700XT | **Ryzen** 5 (3600x) | **B450 Motherboard** | 16GB Memory (2x8GB)

**Comment by flibitijibibo** [comment]
I'm not seeing any relationship to FNA here - maybe it's WASAPI? In any case, the TML devs will need to handle this, they use a lot of custom stuff we don't want to run support for.
