### ISSUE TITLE
undefined reference to wrap_io_read

### ISSUE THREAD

**Issue by Elkasitu** [FNA-XNA/FAudio#29]
Hello,

I followed the `README` on compiling the native dlls with `mingw`; most of the DLLs compile fine except the `xactengine` ones, while compiling I get the following error:

```
x86_64-w64-mingw32-g++ -I../src -DFAUDIOCPP_EXPORTS -D_WIN32_WINNT=0x0600 `sdl2-config --cflags` -shared -o build_win64/xactengine3_0.dll build_win64/com_utils_xact_x30.o build_win64/xact3_x30.o build_win64/win_registry_x30.o build_win64/xactdll_x30.o -Wl,--enable-stdcall-fixup `sdl2-config --libs` -static-libgcc -static-libstdc++ -L.. -lFAudio
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: build_win64/xact3_x30.o:xact3.cpp:(.rdata$.refptr.wrap_io_close[.refptr.wrap_io_close]+0x0): undefined reference to `wrap_io_close'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: build_win64/xact3_x30.o:xact3.cpp:(.rdata$.refptr.wrap_io_seek[.refptr.wrap_io_seek]+0x0): undefined reference to `wrap_io_seek'
/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/../../../../x86_64-w64-mingw32/bin/ld: build_win64/xact3_x30.o:xact3.cpp:(.rdata$.refptr.wrap_io_read[.refptr.wrap_io_read]+0x0): undefined reference to `wrap_io_read'
collect2: error: ld returned 1 exit status
make: *** [Makefile:204: build_win64/xactengine3_0.dll] Error 1
```

I read the commit history on `xact3.cpp` and deemed it "normal" since it's untested code, so I tried copying the `xaudio2` dlls into my Skyrim Special Edition prefix (no NPC voice sound problem) with the script provided in `/scripts` anyway but there's no in-game sound at all.

Here's the Skyrim steamlog in case it's of any use:
[steam-489830.log](https://github.com/FNA-XNA/FAudio/files/2325084/steam-489830.log)

**Comment by flibitijibibo** [comment]
Build fixed by https://github.com/FNA-XNA/FAudio/commit/b4fd8110a6214d11f3cc61c43a89ad9f299a81e6.

Note that Skyrim's not going to work until Andrew gets the xWMA support in. Most of the data is going to get skipped and so I imagine a lot (if not all) of the game is going to be totally quiet. Stuff like that is tracked over at https://github.com/ValveSoftware/wine/issues/2.
