### ISSUE TITLE
Assertion failed, no output channels

### ISSUE THREAD

**Issue by Chicken-Bones** [FNA-XNA/FAudio#296]
`Assertion failed: voice->outputChannels > 0 && voice->outputChannels < 9, file FAudio\src\FAudio.c, line 1227`
`Running on Windows (v10.0.19044.0) X64 NetCore 6.0.5`

FAudio built with the win32 (windows media feature pack) backend.
User reports that disabling https://www.voicemod.net/ fixed the crashes.
User experiences issue after random amount of playtime, not at startup.

I'm assuming that `outputChannels == 0`, will attempt to confirm.

FAudio should run silently if there are no output channels rather than crash, looking for some pointers where to start on this. 

On a related note, FAudio currently doesn't recover from `AUDCLNT_E_DEVICE_INVALIDATED` which can be returned from most `IAudioClient` methods. Unfortunately the audio device is baked into the audio thread, so I'm not sure on a good place to implement the recovery process mentioned in https://docs.microsoft.com/en-us/windows/win32/coreaudio/recovering-from-an-invalid-device-error

**Comment by flibitijibibo** [comment]
The FAudio core error is doing its job in this case, so we're looking at something in Win32 device enumeration or creation, and that file's more for Wine than anything else. Assigned to Remi but feel free to pass it to anyone working on Wine audio right now...

**Comment by Chicken-Bones** [comment]
In case it matters, this user is not using Wine. Native Windows install.

**Comment by cyraid** [comment]
@flibitijibibo why is there a wine label on this issue? Is this issue being worked on? It's quite the doozy if it crashes the entire app/game when someone just switched audio (unplugs, gets up for a break and Bluetooth headset turns off and it crashes etc)

**Comment by thatcosmonaut** [comment]
We do not support tModLoader. If you can reproduce this issue with a vanilla FNA application feel free to reopen this issue.

**Comment by flibitijibibo** [comment]
I think on SDL's end this got fixed via https://github.com/libsdl-org/SDL/commit/eb1b9b418cbcc777207e7b1672c7fe94df3bcd11
