### ISSUE TITLE
Compiler warning in FAudio_internal_simd, cast from pointer to integer of different size

### ISSUE THREAD

**Issue by aeikum** [FNA-XNA/FAudio#30]
Building the new `FAudio_internal_simd.c` in 32-bit mode shows some warnings:

```../../../wine/dlls/xaudio2_7/FAudio/FAudio_internal_simd.c: In function ‘FAudio_INTERNAL_ResampleMono_SSE2’:
../../../wine/dlls/xaudio2_7/FAudio/FAudio_internal_simd.c:421:33: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  uint32_t tail, header = (16 - ((uint64_t) (*resampleCache)) % 16) / 4;
```

Similar warnings in FAudio_INTERNAL_ResampleStereo_SSE2 and FAudio_INTERNAL_Amplify_SSE2. Changing to uint32_t fixes the warning, though I'm not sure if that's correct.

**Comment by flibitijibibo** [comment]
Does changing it to `size_t` fix the problem?

**Comment by aeikum** [comment]
Boy, that's obvious in retrospect. Yes, it does.

**Comment by flibitijibibo** [comment]
Alrighty, pushing the change now!

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FAudio/commit/0f314a7d2f0483db18efa79908666226d1b1dbf8

I think that covers it but my compiler wasn't warning before, so send over any fixes if I didn't get this!

**Comment by aeikum** [comment]
All clean, thanks. FWIW this was with gcc 8.2.0 as shipped by Arch Linux.
