### ISSUE TITLE
FFXIV Endwalker Benchmark no audio and crashes in xaudio2_7 on exit

### ISSUE THREAD

**Issue by kotarou3** [FNA-XNA/FAudio#300]
(Identically reported to https://bugs.winehq.org/show_bug.cgi?id=53799 in case this is just a wine problem)

The application in question can be downloaded from https://jp.finalfantasyxiv.com/benchmark/download/ (Direct link: https://download.finalfantasyxiv.com/ys8glaimvmykn88p/ffxiv-endwalker-bench.zip)

It can be executed with the following command line (not enough arguments to fully configure the benchmark, but enough to demonstrate the problem):

    wine game/ffxiv_dx11.exe SYS.Language=1

When the application is running, no audio is heard when there should be audio.
And when it exits (such as closing the window, pressing ESC, or letting it finish), it will segfault in xaudio2_7 with the following backtrace ([full output](https://github.com/FNA-XNA/FAudio/files/9794235/console.log)):

```
=>0 0x00000242e0aeac FAudio_AudioClientThread+0xcc(user=00000000010301B0) [Z:\tmp\wine-src\libs\faudio\src\FAudio_platform_win32.c:190] in xaudio2_7 (0000000000000000)
  1 0x0000007b629109 BaseThreadInitThunk+0x9(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [Z:\tmp\wine-src\dlls\kernel32\thread.c:61] in kernel32 (0000000000000000)
  2 0x0000017005eda3 __wine_pop_frame(entry=0000000242E0ADE0, arg=00000000010301B0) [Z:\tmp\wine-src\include\wine\exception.h:277] in ntdll (0000000000000000)
  3 0x0000017005eda3 RtlUserThreadStart+0x83(entry=[<register RSP not accessible in this frame>, arg=[<register RSP not accessible in this frame>) [Z:\tmp\wine-src\dlls\ntdll\thread.c:240] in ntdll (0000000000000000)
0x00000242e0aeac FAudio_AudioClientThread+0xcc [Z:\tmp\wine-src\libs\faudio\src\FAudio_platform_win32.c:190] in xaudio2_7: movq (%rcx),%rax
190             FAudio_assert(!FAILED(hr) && "Failed to stop IAudioClient!");
```

This was run in a clean WINEPREFIX with wine-7.19 freshly built from source.

If I use winetricks to install xact_x64 (i.e., bypassing FAudio), the crash goes away, but there is still no audio output

**Comment by flibitijibibo** [comment]
Double checked the Bugzilla thread and it looks like FAudio's clear - the audio was winepulse not handling the specific hardware (pro audio with 10+ channels) and the crash on exit is actually wined3d (the backtrace in the OP is the assert doing its job!).

If this comes back around to FAudio somehow this can be reopened.
