### ISSUE TITLE
FAudio versions after 22.07 cause popping

### ISSUE THREAD

**Issue by Kleadron** [FNA-XNA/FAudio#306]
The versions of FAudio I have tested from fnalibs are 23.02 and 22.07.
Everything else from fnalibs is from the latest 23.02 release, including SDL2.

I am running FortressCraft Chapter 1 on 64-bit windows, with 44.1khz 16-bit windows audio output, and I have provided two 30 second sample wave files of audio showcasing some of the in-game music. There seems to be an interval where the popping occurs. All music tracks are implemented with a Sound Effect, no compressed files or streaming are used.

[music samples.zip](https://github.com/FNA-XNA/FAudio/files/10832451/music.samples.zip)

audio_good.wav is from FAudio 22.07, and audio_bad.wav is from FAudio 23.02.

**Comment by flibitijibibo** [comment]
Forwarding to https://github.com/libsdl-org/SDL/issues/5538
