### ISSUE TITLE
[On Hold] FAUDIO_PLATFORM_WASAPI

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/FAudio#31]
This is mostly for Wine, but also has to do with our own COM wrapper.

@aeikum has already started work on this, though it depends specifically on Wine atm:

https://github.com/aeikum/FAudio/commit/9372b37e6c38b6b2f3c6ce7d1d39dbc10b807bdc

That said, the only dependency is `wine/heap.h`, and I'm 99% sure that can be fixed by using `CoTaskMemAlloc` for FAudio_malloc, which I'm pretty sure is what XAudio2/XACT are using:

https://github.com/FNA-XNA/FAudio/blob/344dd5535c3dff5decbf2335da374f8ad1499bc1/cpp/XAPOBase.cpp#L78
https://github.com/FNA-XNA/FAudio/blob/38471d2267f8f63598d367c984f0123a7fe54177/src/FACT.c#L2328

**Comment by flibitijibibo** [comment]
Played with some XAudio2 games today and CoTaskMem is definitely what's getting used, so for our COM wrapper I've got this set up now:

https://github.com/FNA-XNA/FAudio/commit/aa1f54185e7ce8a76c860da452c1c16c316293b1

A Wine path would just use these by default.

**Comment by flibitijibibo** [comment]
This sortakinda got blown apart by the removal of our attempt to make a Wine builtin ourselves; the platform being built here is more of a Wine platform and not necessarily a Win32 platform; the two could probably coexist with a bunch of ifdefs, but at the same time it's more likely that Windows users will want to just use SDL if they're going to the effort of not using the official XAudio2 libs.

Andrew and I can deal with this separately as a Wine issue, not an FAudio general issue.

**Comment by flibitijibibo** [comment]
Reviving this, I think I can make a WASAPI backend that works as a Wine built-in without any fuss. Branch is here:

https://github.com/FNA-XNA/FAudio/tree/wasapi

**Comment by flibitijibibo** [comment]
Spent the afternoon getting the WASAPI target back in order, this is how it looks as of today:

https://github.com/FNA-XNA/FAudio/blob/e57f21fb38d49610cec90ca0963fb2d19b628c3c/src/FAudio_platform_wasapi.c

This is mostly based on Andrew's work, but the way I wrote this was rewriting it line-by-line so I could learn absolutely every line of the implementation, and rework things I was unsure of. Some changes were for FAudio feature completeness, some was some unintentional brokenness, some came from my experience with WASAPI in SDL, limited as it may be...

This revision compiles and links, and test programs boot and run! Unfortunately they're totally silent. Nothing like the audio equivalent of a black screen! I'm not sure why this is but I'm sure it's obvious, but code like this can be difficult to read no matter how strict you are with style (yay low-level C).

**Comment by flibitijibibo** [comment]
Okay, I finally got this to work - everything except submixes should work, since I need to implement the resampler. I'll see if I can't shove in the linear resampler as a temp solution today, and later on we can figure out a better way to have fixed-rate SRC here. (Maybe write our own...?)

**Comment by flibitijibibo** [comment]
Going to close this... in the general case I think SDL2 will hold up better (and those that need WASAPI will probably know what they're doing) and in Wine's case it may be smarter to go one level deeper and try to fix this in SDL instead (i.e. make the Win32 backends libwine-compatible).

My code eventually ended up being a ripoff of SDL's anyhow, so there's not much of value in there.

**Comment by aeikum** [comment]
I still think there's value in this. For example, the default device selection in winecfg will no longer work for xaudio2 games. It's easy to imagine a game which depends on getting valid device IDs across various Windows APIs. Also, Wine's multichannel support appears to be better than SDL's.

The idea of building SDL's win32 backends on Linux to use via Wine is interesting, but it does create a weird build-time dependency loop.
