### ISSUE TITLE
Does this library support Android version? If supported, how to compile it?

### ISSUE THREAD

**Issue by SaintZhao** [FNA-XNA/FAudio#310]
I try to compile the Android version of the library, but the following error occurs：

[  5%] Building C object CMakeFiles/FAudio.dir/src/F3DAudio.c.o
In file included from G:\Game_Development\FAudio\src\F3DAudio.c:28:
G:\Game_Development\FAudio\src/FAudio_internal.h:112:10: fatal error: 'SDL_stdinc.h' file not found
#include <SDL_stdinc.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/FAudio.dir/src/F3DAudio.c.o] Error 1
make[1]: *** [CMakeFiles/FAudio.dir/all] Error 2
make: *** [all] Error 2

It seems that another dependency library，that is SDL, needs to be added. I don't know yet how to add it. Can someone help me?

**Comment by flibitijibibo** [comment]
The FNA libraries generally do not support Android, but we don't necessarily _block_ Android from compiling - it's important to have the SDL dependency somewhere; CMake tries to find it but worst case you can add the SDL include/library folders manually to whatever build system Android has these days...

**Comment by SaintZhao** [comment]
Can you provide me a “CMakeLists.txt” that supports compiling android version? Thanks a lot.

**Comment by SaintZhao** [comment]
Ok, i got it. Thank you very much for your reply.
