### ISSUE TITLE
Spider-Man: Shattered Dimensions - dialogue audio doesn't play

### ISSUE THREAD

**Issue by SuperSamus** [FNA-XNA/FAudio#312]
(Also reported on https://bugs.winehq.org/show_bug.cgi?id=54720, in case it's not an FAudio issue.)

In Spider-Man: Shattered Dimensions, the audio that is supposed to be played by the characters during in-game dialogues doesn't play.
All the other kinds of audio work (including audio during pre-rendered cutscenes).

Installing `xact` with winetricks makes the dialogue audio work.

Logs taken with a clean 32 bit prefix with 32 bit Wine devel 8.4 and `WINEDEBUG=+xaudio2`.
[SpiderLogs.txt](https://github.com/FNA-XNA/FAudio/files/11231842/SpiderLogs.txt)
(The game logs even at the start when there is no problem, start from the end of the file)

**Comment by flibitijibibo** [comment]
I would guess that it's xWMA and that the GStreamer plugin isn't present.

**Comment by SuperSamus** [comment]
Alright, I have taken them again, this time with tkg 8.5.
[SpiderLogs2.txt](https://github.com/FNA-XNA/FAudio/files/11233336/SpiderLogs2.txt)

`GStreamer doesn't support WMA decoding` is gone, and the issue persists, so it's not that.
I'm sure that the error is not on my end because looking on the internet, multiple people (even with Steam Deck) say that `xact` needs to be installed for the dialogue to work.

(There is a part full of GStreamer errors that end with `wrong ELF class: ELFCLASS64`. Ignore them.)

**Comment by flibitijibibo** [comment]
Looks like it is indeed related to MediaFoundation, there are a few messages like this one during voice processing:
```
0180:fixme:wmadec:transform_ProcessMessage iface 01EC70BC, message 0x10000003, param 00000000 stub!
0180:err:mfplat:wg_sample_release wg_sample 01F19FD0 is still in use, trouble ahead!
```
