### ISSUE TITLE
OpenBSD: assertion failure at FAudio_memptr

### ISSUE THREAD

**Issue by rfht** [FNA-XNA/FAudio#33]
Hi,

When trying Owlboy with newest FNA 18.10 and locally compiled FAudio, the game gets this assertion failure when the main menu is about to be displayed:

```
Assertion failure at FAudio_memptr (src/FAudio_platform_sdl2.c:587), triggered 1 time:
  'rwops->type == 4U'
```

This was preceded before the intro video by:

```
Assertion failure at FACT_INTERNAL_ParseWaveBank (src/FACT_internal.c:2709), triggered 1 time:
  'wb->streaming == isStreaming'
```

However, this ParseWaveBank failure didn't stop the program and sound was played afterwards.

Any hints where I can start to troubleshoot this?

**Comment by flibitijibibo** [comment]
This is on me; I have some Owlboy WaveBanks marked as streaming when they shouldn't be. What you can do is go to that assert and set `wb->streaming = isStreaming` and both asserts should go away (and the game should run just fine).

**Comment by rfht** [comment]
Will this be fixed in Owlboy with an update? Or will FAudio need to accomodate here? It would be a little impractical to have a separate build of FAudio just for this, it would seem...

**Comment by flibitijibibo** [comment]
I'll update Owlboy at some point, not sure when yet. I thought about setting wb->streaming after the assert but I dunno if that's safe to do with WMA yet. Once we have WMA support done for Wine I'll be able to say for sure that it's either safe to override or requires an update to the games I tweaked (I think it's just Owlboy, Apotheon and Cryptark I did this for?).

**Comment by rfht** [comment]
In the meantime, is it safe to run everything with `wb->streaming = isStreaming`? Or will other games break? In that case, I'll keep 2 versions of libFAudio around for now.

**Comment by flibitijibibo** [comment]
AFAIK it should be safe with PCM/ADPCM, so if you want to include a patch in your packages that should be okay. If you want to avoid asserts you can compile with O2+ and the SDL_ASSERT_LEVEL should bump up one level and skip any popups.

**Comment by rfht** [comment]
Thanks, I didn't know this was affected by `-O2` compiler flag. The package for OpenBSD should/will be set up to use -O2 anyway.

The time window before OpenBSD 6.4-release is closing, but I hope to get some testing in before then.

**Comment by rfht** [comment]
Okay, with adding a patch to set `wb->streaming = isStreaming` and building with `-O2`, Owlboy works just fine and audio is great. :+1:
