### ISSUE TITLE
Stable release assets

### ISSUE THREAD

**Issue by rfht** [FNA-XNA/FAudio#34]
Hi,

Any chance a release could be tagged, ideally along with an upload of a tar-{xz,bz2,gz} of the files? Background is that GitHub makes the auto-generated packages on the fly and changes their formula without notice, so having an automated ports system like on OpenBSD that check SHA256 and file sizes before building breaks regularly and messes up the package build system with the auto-generated tarballs.

Similar to this question in the Theorafile repo:

https://github.com/FNA-XNA/Theorafile/issues/2

**Comment by flibitijibibo** [comment]
Same story as Theorafile, but with FAudio the version numbers are exactly the same as FNA's, so the FAudio version that got bundled with FNA 18.10 is also versioned as 18.10. Release notes will be documented with the FNA releases, and even if FNA doesn't have any changes, a release will still come out if FAudio has changes from the previous month.

**Comment by rfht** [comment]
Thanks - I should have looked - somehow I was under the impression that FAudio wasn't in there; and that it only was available precompiled in the fnalibs archive.

Right, now I see it's there in the lib directory...
