### ISSUE TITLE
SDL3 support

### ISSUE THREAD

**Issue by TylerGlaiel** [FNA-XNA/FAudio#340]
Current version of FAudio won't work if you provide SDL3 instead of SDL2

(I'm working on porting it myself for now, but if there's a fork that does this already please let me know!)

**Comment by flibitijibibo** [comment]
I haven't started it yet so I believe you're the first to look at it - I think if FAUDIO_PLATFORM_SDL3 is used it should allow for reusing the stuff in FAudio_internal.h and should allow for a new FAudio_platform_sdl3.c without sdl2.c conflicting.

**Comment by TylerGlaiel** [comment]
there's a few nasty hacks in there that seemed specific to SDL2 that also bled outside of FAudio_platform_sdl2.c a bit, mainly this one, that I'm having trouble figuring out how to migrate without doing some really annoying stuff. I might just return NULL for now and hope it doesnt crash on anything im doing...

uint8_t* FAudio_memptr(FAudioIOStream *io, size_t offset)
{
	SDL_RWops *rwops = (SDL_RWops*) io->data;
	FAudio_assert(rwops->type == SDL_RWOPS_MEMORY);
	return rwops->hidden.mem.base + offset;
}

**Comment by flibitijibibo** [comment]
I think the IOStreams are all for FACT so it shouldn't affect regular audio use. I do wonder how we get the raw pointer from SDL_IOStream though, maybe it's a property now?

**Comment by TylerGlaiel** [comment]
if the raw pointer is only ever used when initialized from FAudio_memopen, to me it seems like the raw pointer should just be stored in FAudioIOStream directly for the cases where you'd need that...

**Comment by flibitijibibo** [comment]
Looks like it is indeed a property: https://github.com/libsdl-org/SDL/blob/main/include/SDL3/SDL_iostream.h#L309

For now I would skip the IOStream stuff, I can take care of that later.

**Comment by TylerGlaiel** [comment]
i have it outputting audio just fine currently, except for if I switch audio devices while it's outputting, I get a stack overrun on this (taken from the SDL3 migration guide) when I switch back to the original device

![image](https://github.com/FNA-XNA/FAudio/assets/1686664/07742584-0a85-49e1-88c4-e8829059b486)

switching it from stack alloc to malloc prevents it (though uh, not a good solution)

there doesnt seem to be anything anomalous about whats getting passed to "additional_amount" there when it crashes

padding the allocated buffer by 64 also prevents the crash.
something either in MixCallback or PutAudioStreamData is reading or writing past the end of the data?

**Comment by TylerGlaiel** [comment]
oh wait, Faudio is expecting a fixed updateSize per callback, additional_amount doesnt even get propogated to update_internal

**Comment by TylerGlaiel** [comment]
well this is functional, if a bit messy (was mostly concerned with simply getting it functional since it was blocking me being able to test migrating the rest of my project to SDL3). theres a lot of things I'm confused on or ignored (like, subtracting 1 from device indexes and stuff that I have no idea is relevant or not anymore, and don't even know what setups that should be tested on anyway)

https://github.com/TylerGlaiel/FAudio-sdl3

**Comment by flibitijibibo** [comment]
Will try to integrate this tomorrow or Monday - for the most part it looks like the stuff we care about just got renamed and the default is no longer just device 0, but that won't be hard to re-do. The notable part of the callback replacement is that we'll mostly ignore additional since XAudio insists on the block size, so we'll call the mix function based on additional / wantsamples rather than mixing with varying block sizes.

**Comment by flibitijibibo** [comment]
Applied most of your changes into upstream:

https://github.com/FNA-XNA/FAudio/blob/master/src/FAudio_platform_sdl3.c

Feel free to patch things up if I broke it, the idea is that we the platform device handle is now a struct which holds both the FAudio object as well as a staging buffer, so we don't have to alloca() for every callback.

**Comment by TylerGlaiel** [comment]
yeah seems like it works, one thing I omitted that was in the SDL2 version was, in FAudio_PlatformInit, there was a separate "want" and "have" for the audio format, in SDL3 I ignored the "have" part entirely since that wasn't part of the new Open Device api, and I'm unsure if it could internally be different

**Comment by flibitijibibo** [comment]
As of https://github.com/FNA-XNA/FAudio/commit/074d46e33d79d004af6cc6a8ca1050d4b18debc5 SDL3 should fully work now - once 3.0 is tagged we'll add sdl3.c to the project files and add the define!
