### ISSUE TITLE
Call to undeclared function 'FAudio_memcpy'

### ISSUE THREAD

**Issue by Wolftein** [FNA-XNA/FAudio#356]
Got a bunch of issues when trying to compile FAudio with SDL3 using Clang for Android.

> C:\Users\Agustin\Workspace\Aurora\bin\_deps\external_faudio-src\src/stb.h:252:4: error: call to undeclared function 'FAudio_memcpy'; ISO C99 and later do not support implicit function
      declarations [-Wimplicit-function-declaration]
  252 |    memcpy(buffer, p     , sz);
      |    ^
C:\Users\Agustin\Workspace\Aurora\bin\_deps\external_faudio-src\src/stb.h:214:16: note: expanded from macro 'memcpy'
  214 | #define memcpy FAudio_memcpy
      |                ^
C:\Users\Agustin\Workspace\Aurora\bin\_deps\external_faudio-src\src/FAudio_internal.h:144:39: note: expanded from macro 'FAudio_memcpy'
  144 | #define FAudio_memcpy(dst, src, size) SDL_memcpy(dst, src, size)
      |                                       ^
C:\Users\Agustin\Workspace\Aurora\bin\_deps\external_sdl-src\include/SDL3/SDL_stdinc.h:931:21: note: expanded from macro 'SDL_memcpy'
  931 | #define SDL_memcpy  memcpy

**Comment by apartfromtime** [comment]
Same issues with SDL3 on windows.

**Comment by flibitijibibo** [comment]
Odd, I thought SDL_memcpy was always declared in the 3.0 headers - basically what we're doing is redefining memcpy (only in stb!) to be FAudio_memcpy, and FAudio_memcpy should be defined to SDL_memcpy.

**Comment by apartfromtime** [comment]
To compile I had to comment out wherever memcpy\memset were redefined to FAudio_memcpy \FAudio_memset.

https://github.com/FNA-XNA/FAudio/blob/a3b8bf748157462ee951376f483a8577de40f24e/src/stb.h#L214
https://github.com/FNA-XNA/FAudio/blob/a3b8bf748157462ee951376f483a8577de40f24e/src/XNA_Song.c#L39
https://github.com/FNA-XNA/FAudio/blob/a3b8bf748157462ee951376f483a8577de40f24e/src/XNA_Song.c#L43

**Comment by flibitijibibo** [comment]
https://github.com/FNA-XNA/FAudio/commit/0cf2bce5159367332f6bdfe8342998d3f4313880
