### ISSUE TITLE
WINE binary release

### ISSUE THREAD

**Issue by dhewg** [FNA-XNA/FAudio#39]
How about providing binary releases? That would widen the audience considerably!

What's easy, works and known is the [winetricks](https://github.com/Winetricks/winetricks) verb facility, like [dxvk](https://github.com/doitsujin/dxvk/blob/master/utils/setup_dxvk.verb) is using.

**Comment by flibitijibibo** [comment]
Not until WMA support is done. No way am I opening the floodgates for more people complaining about Skyrim support...

**Comment by flibitijibibo** [comment]
I'm going to close this in favor of https://github.com/ValveSoftware/wine/issues/2. By the time FAudio is good enough to ship as a binary release, it should probably be good enough to try as a Wine built-in. I'll be focusing on that while the WMA stuff gets done separately.
