### ISSUE TITLE
Error when building FAudio

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [FNA-XNA/FAudio#51]
First, I am average Linux user, and I use Manjaro KDE latest stable version.

I installed the required Mingw 64 libraries

![screenshot_20181103_223340](https://user-images.githubusercontent.com/29783425/47957111-f445ed00-dfb8-11e8-9057-ed98db7f4554.png)

then tried to compile FAudio as described at Readme.md, and got this error about FAudio.dll not found

`[ahmed@ahmed-pc FAudio-master]$ make clean all
rm -f src/F3DAudio.o src/FAudio.o src/FAudio_internal.o src/FAudio_internal_simd.o src/FAudioFX_reverb.o src/FAudioFX_volumemeter.o src/FACT.o src/FACT3D.o src/FACT_internal.o src/FAPOBase.o src/FAPOFX.o src/FAPOFX_eq.o src/FAPOFX_masteringlimiter.o src/FAPOFX_reverb.o src/FAPOFX_echo.o src/FAudio_platform_sdl2.o src/XNA_Song.o ./libFAudio.so testparse facttool testreverb testvolumemeter testfilter
cc -fpic -fPIC -g -Wall -pedantic -c -o src/F3DAudio.o src/F3DAudio.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAudio.o src/FAudio.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAudio_internal.o src/FAudio_internal.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAudio_internal_simd.o src/FAudio_internal_simd.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAudioFX_reverb.o src/FAudioFX_reverb.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAudioFX_volumemeter.o src/FAudioFX_volumemeter.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FACT.o src/FACT.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FACT3D.o src/FACT3D.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FACT_internal.o src/FACT_internal.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAPOBase.o src/FAPOBase.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAPOFX.o src/FAPOFX.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAPOFX_eq.o src/FAPOFX_eq.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAPOFX_masteringlimiter.o src/FAPOFX_masteringlimiter.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAPOFX_reverb.o src/FAPOFX_reverb.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAPOFX_echo.o src/FAPOFX_echo.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/FAudio_platform_sdl2.o src/FAudio_platform_sdl2.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -c -o src/XNA_Song.o src/XNA_Song.c `sdl2-config --cflags`
cc -fpic -fPIC -g -Wall -pedantic -shared -o ./libFAudio.so src/F3DAudio.o src/FAudio.o src/FAudio_internal.o src/FAudio_internal_simd.o src/FAudioFX_reverb.o src/FAudioFX_volumemeter.o src/FACT.o src/FACT3D.o src/FACT_internal.o src/FAPOBase.o src/FAPOFX.o src/FAPOFX_eq.o src/FAPOFX_masteringlimiter.o src/FAPOFX_reverb.o src/FAPOFX_echo.o src/FAudio_platform_sdl2.o src/XNA_Song.o `sdl2-config --libs`
[ahmed@ahmed-pc FAudio-master]$ source cpp/scripts/cross_compile_64
Please check your mingw32 SDL installation
[ahmed@ahmed-pc FAudio-master]$ cd cpp
[ahmed@ahmed-pc cpp]$ make
mkdir -p build_win64
cp ../FAudio.dll build_win64
cp: cannot stat '../FAudio.dll': No such file or directory
make: *** [Makefile:241: directories] Error 1
`

**Comment by mikedebian** [comment]
make mkdir -p build_win64 cp ../FAudio.dll build_win64 cp: cannot stat '../FAudio.dll': No such file or directory make: ***

Are you sure you got the right location for the file? It can't find it, thus can't copy it, or am I missing some information here that I can't see?

**Comment by ahmed-elsayed2017** [comment]
There is `FAudio.dll` file created in the main folder, there is `libFAudio.so` that had been created in the first step.

**Comment by mikedebian** [comment]
So, you meant to create a linux library, right? Because if so, you need libFAudio.so.

If you want to create a Windows DLL, you use FAudio.dll.

I believe you intend to do the first. So, but libFAudio.so in build_wine64 (NOT build_win64. Lacking an 'e' there)

**Comment by flibitijibibo** [comment]
```
cd FAudio/
make
cd cpp/
make -f Makefile.wine
cp ../libFAudio.so build_wine64/
cd ..
CFLAGS="-m32" make clean all
cd cpp/
ARCH=32 make -f Makefile.wine
cp ../libFAudio.so build_wine64/
```

It will then be up to you do install these to a custom Proton installation. If the above doesn't work or you don't know how to make custom Proton installation, please wait until the FAudio Wine patches are finished.

**Comment by ahmed-elsayed2017** [comment]
make -f Makefile.wine ended with an error, but I feel that you don't care about my feedback. Thanks anyway.
