### ISSUE TITLE
COM wrapper callback crashes only as a Wine built-in

### ISSUE THREAD

**Issue by flibitijibibo** [FNA-XNA/FAudio#67]
Here's a really strange bug... this one's for @aeikum, @JohanSmet, and possibly @GloriousEggroll.

We're having trouble diagnosing a crash in various games related to callbacks, and the more I dig into it the more confused I get! For today's example, we have a LEGO-themed Wolfenstein 3D fan remake, which among other things is simple enough to run through Valgrind:

http://drdanick.com/legowolf3d/

When using the COM wrapper everything should be okay, but when you build it as a Wine DLL, the program randomly crashes! This also happens with [our Wine built-ins](https://github.com/flibitijibibo/wine/pull/1). I'm not 100% sure what the difference might be, other than the usual suspects (calling conventions, packing/alignment, etc).

The crash happens only when OnBufferStart/OnBufferEnd is referenced, so if you comment those bits out in the wrapper, the game should be okay (but also silent). Other samples may be affected by different callbacks, depending on what the application cares about. Andrew has a list of games crashing right now, but we don't know if it's all the same bug.

**Comment by flibitijibibo** [comment]
We're still putting together a fix for this and we're only 99% sure it's the problem, but Andrew and I believe the problem has to do with the SDL pthread conflicting with the Wine threads, and the very particular way that everything works there... this isn't actually the first time this has happened, with gstreamer being one example:

https://github.com/wine-mirror/wine/commit/56b6523842f8fd9125f6d3c1651d836163dfef00

Current plan is to introduce an extension to give applications the chance to provide its own thread for engine updates, but since the platform thread is off-limits to us (for more reasons than one) we'll have to come up with something a little more clever than just overriding a platform function. We'll post again when there's something to look at.

**Comment by aeikum** [comment]
Created #69 for this.

**Comment by flibitijibibo** [comment]
Fixed by #69
