### ISSUE TITLE
The Witcher 3: Sound issue with Esync turned on

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [FNA-XNA/FAudio#98]
The sound is so buggy when I play The Witcher 3 with Esync turned on, but when it is off everything is working fine. I think it is worth mentioning because it could help you bisecting the issue.

**Comment by flibitijibibo** [comment]
That sounds like an esync issue, not FAudio...? You've isolated it specifically to esync.

In any case, you'll want to file this in the Witcher 3 Proton report: https://github.com/ValveSoftware/Proton/issues/607
