### ISSUE TITLE
Hellblade crashes at the beginning

### ISSUE THREAD

**Issue by ahmed-elsayed2017** [FNA-XNA/FAudio#99]
Hellblade crashes at the beginning with Faudio.

**Crash log:**
`0031:fixme:ntdll:EtwEventRegister ({5eec90ab-c022-44b2-a5dd-fd716a222a15}, 0x14000107c, 0x140016030, 0x140016050) stub.
0031:fixme:ntdll:EtwEventSetInformation (deadbeef, 2, 0x140013988, 43) stub
0033:err:module:import_dll Library libaom.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libgsm.dll.1.0.14 (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libiconv-2.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library liblzma-5.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libmp3lame-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libopencore-amrnb-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libopencore-amrwb-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libopenjp2-7.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libopus-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libspeex-1.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libtheoradec-1.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libtheoraenc-1.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libvorbis-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libvorbisenc-2.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libvpx.dll.5.0.0 (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libwebp-7.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libwebpmux-3.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libx264-148.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libx265.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library zlib1.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library xvidcore.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libsoxr.dll (which is needed by L"C:\\windows\\system32\\swresample-3.dll") not found
0033:err:module:import_dll Library swresample-3.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library avcodec-58.dll (which is needed by L"C:\\windows\\system32\\FAudio.dll") not found
0033:err:module:import_dll Library libssp-0.dll (which is needed by L"C:\\windows\\system32\\FAudio.dll") not found
0033:err:module:import_dll Library FAudio.dll (which is needed by L"C:\\windows\\system32\\X3DAudio1_7.dll") not found
0033:err:module:import_dll Library X3DAudio1_7.dll (which is needed by L"Z:\\mnt\\Games\\Hellblade Senuas Sacrifice\\HellbladeGame\\Binaries\\Win64\\HellbladeGame-Win64-Shipping.exe") not found
0033:err:module:import_dll Library libssp-0.dll (which is needed by L"C:\\windows\\system32\\XAPOFX1_5.dll") not found
0033:err:module:import_dll Library libaom.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libgsm.dll.1.0.14 (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libiconv-2.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library liblzma-5.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libmp3lame-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libopencore-amrnb-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libopencore-amrwb-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libopenjp2-7.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libopus-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libspeex-1.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libtheoradec-1.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libtheoraenc-1.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libvorbis-0.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libvorbisenc-2.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libvpx.dll.5.0.0 (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libwebp-7.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libwebpmux-3.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libx264-148.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libx265.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library zlib1.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library xvidcore.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library libsoxr.dll (which is needed by L"C:\\windows\\system32\\swresample-3.dll") not found
0033:err:module:import_dll Library swresample-3.dll (which is needed by L"C:\\windows\\system32\\avcodec-58.dll") not found
0033:err:module:import_dll Library avcodec-58.dll (which is needed by L"C:\\windows\\system32\\FAudio.dll") not found
0033:err:module:import_dll Library libssp-0.dll (which is needed by L"C:\\windows\\system32\\FAudio.dll") not found
0033:err:module:import_dll Library FAudio.dll (which is needed by L"C:\\windows\\system32\\XAPOFX1_5.dll") not found
0033:err:module:import_dll Library XAPOFX1_5.dll (which is needed by L"Z:\\mnt\\Games\\Hellblade Senuas Sacrifice\\HellbladeGame\\Binaries\\Win64\\HellbladeGame-Win64-Shipping.exe") not found
0033:err:module:LdrInitializeThunk Importing dlls for L"Z:\\mnt\\Games\\Hellblade Senuas Sacrifice\\HellbladeGame\\Binaries\\Win64\\HellbladeGame-Win64-Shipping.exe" failed, status c0000135
0031:fixme:kernelbase:AppPolicyGetProcessTerminationMethod 0xfffffffffffffffa, 0x5ffd00
`

**Comment by flibitijibibo** [comment]
Wait a minute, you're not even using Proton for this...? FAudio.dll implies a native lib, 3.16-5 uses a native library. This is probably why esync introduces a problem, the same thing happens with dsound streams.

Again, Proton issue: https://github.com/ValveSoftware/Proton/issues/943

**Comment by ahmed-elsayed2017** [comment]
I don't use Proton. I use Wine with the Faudio-wrappers, and turnning Esync off doesn't help running the game.

**Comment by flibitijibibo** [comment]
You’re looking for this: https://github.com/flibitijibibo/wine/pull/1

**Comment by ahmed-elsayed2017** [comment]
I am using something else, but Where can I report an issue when I am using the other branch?

**Comment by flibitijibibo** [comment]
Ask the maintainers of that branch.

**Comment by ahmed-elsayed2017** [comment]
I know what was wrong. I used wrappers someone published at AUR, but after I building the wrappers myself, it works like a charm without any error messages, so it was totally my fault.

Even the game that is known to have a lot of audio issues with Wine like Metro Last Light works for the first time properly!

Thank you so much @flibitijibibo  . This is a magnificent work.

**Comment by ahmed-elsayed2017** [comment]
Could you please keep updating the wrappers until it is officially released on Wine?
